text = "Duis eiusmod proident consectetur laborum proident cupidatat ut aute dolor do sit aute mollit reprehenderit."
tags = ["CreativeCoding", "GenerativeArt", "MastoArt"]
asset = "images/cat.jpg"
assetAlt = "a cute little cat stretching its legs"